create table curs (
    id integer generated by default as identity (start with 1) primary key,
    date date
);

create table valutes (
    id varchar (50) primary key,
    num_code varchar (10),
    char_code varchar (10),
    nominal integer ,
    name varchar (100),
    value real,
    curs_id integer references curs(id)
);